### ISSUE TITLE
How to use sentiment analyzer of Greek Spacy?

### ISSUE THREAD

**Issue by CodeBrakes** [eellak/gsoc2018-spacy#10]
Hello and thank you for your work it is amazing. Can you please inform me how to use the sentiment analyzer that you have created? I have installed spacy-nightly and downloaded the el_core_news_md although the submodules for sentiment analysis do not exist there. :/

**Comment by giannisdaras** [comment]
Hi! Thanks for your question. The sentiment analysis system is not part of the official spaCy model (this functionality is not integrated in any spaCy model as far as I am concerned). I guess you are referring to the sentiment analyzer we used for our [nlpbuddy](https://github.com/eellak/nlpbuddy) demo. In this case, could you dig in the documentation and re-open the issue in the nlpbuddy repo if you find any problems?

**Comment by CodeBrakes** [comment]
Yeah i was referring on that. I've managed to figure out a way to run your sentiment analyzer although some words are not well identified due to the lemmatizer and the tokenizer and i am willing to contribute on that. I will open an issue there.
