### ISSUE TITLE
Any instructions how to train NER?

### ISSUE THREAD

**Issue by kagiannis** [eellak/gsoc2018-spacy#6]
Is there any code to produce a model that is trained on the NER provided?
I could train on POS and Dependecies but not on NER.

**Comment by giannisdaras** [comment]
Hello!
Did you try NER training as it is described [here](https://spacy.io/usage/training) and you found any trouble?
If that's not the case, I am not sure whether I would like replicating much info from spaCy docs here, as this project was mainly focused on Greek language integration.
